title: "What Is Truth?"
description: >
  Pontius Pilate asked Jesus Christ "What is truth?" (John 18:38).
  Each of us must ask this question.

url: "https://jacobjivanov.github.io"
baseurl: "/what-is-truth"

theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
