# Site settings
title: "What is Truth?"
description: 'Pontius Pilate asked Jesus Christ this question (John 18:38), and each of us must wrestle with this as well'

# Theme settings
theme: jekyll-theme-minimal




